version: '3.8'

services:
  biblioteca-db:
    image: postgres:15-alpine
    container_name: biblioteca-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=biblioteca
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    volumes:
      - postgres_data:/var/lib/postgresql/data

  biblioteca-backend:
    build: ./backend
    container_name: biblioteca-backend
    ports:
      - "8080:8080"
    depends_on:
      - biblioteca-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://biblioteca-db:5432/biblioteca

  biblioteca-frontend:
    build: ./frontend
    container_name: biblioteca-frontend
    ports:
      - "5173:5173"
    depends_on:
      - biblioteca-backend

  biblioteca-pgadmin:
    image: dpage/pgadmin4
    container_name: biblioteca-pgadmin
    ports:
      - "8081:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=carlos@email.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    depends_on:
      - biblioteca-db

volumes:
  postgres_data: